env:
    GH_TOKEN: ENCRYPTED[!8f85cb8f85dd058e9bd506d3c39df388c3c401e07cc03eb090957e5a6c6f0f0e96b46f71048e78ac75bb6c2d1de59d6f!]
    CIRRUS_SHELL: bash
    CR_NAME: skyhawk
    USERNAME: Sanju0910
    USERMAIL: sreeshankar0910@gmail.com
    CR_REPO: https://github.com/SHRP/manifest.git
    CR_BRANCH: shrp-12.1
    DT_REPO: https://github.com/Sanju0910/skyhawk_device_oneplus_avicii.git
    DT_BRANCH: a12.1_fbev2
    OEM: oneplus
    CODENAME: avicii

task:
  name: "Recovery Build"
  timeout_in: 240m
  container:
      image: ghcr.io/sanju0910/ubuntu:latest
      cpu: 8
      memory: 32G
      
  Sync_script:
      - curl -sL https://raw.githubusercontent.com/Sanju0910/Cirrus_CI/main/scripts/sync.sh | bash

  Build_script:
      - curl -sL https://raw.githubusercontent.com/Sanju0910/Cirrus_CI/main/scripts/build.sh | bash
      
  Deploy_script:
      - curl -sL https://raw.githubusercontent.com/Sanju0910/Cirrus_CI/main/scripts/deploy.sh | bash
